// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'firebase_options.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:

// await Firebase.initializeApp(
//    options: DefaultFirebaseOptions.currentPlatform,
// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArL6Y43ub5UDyY2yGued4H8ZQ5BWBkmes',
    appId: '1:36125817771:web:0647ec8ab5192a813630ee',
    messagingSenderId: '36125817771',
    projectId: 'studentsplacementchatbot',
    authDomain: 'studentsplacementchatbot.firebaseapp.com',
    storageBucket: 'studentsplacementchatbot.appspot.com',
    measurementId: 'G-JF7DDSTF4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmacVg1Cg-FoY1zyrm3O2VyUb-IPrY4_o',
    appId: '1:36125817771:android:3a49041003659aa33630ee',
    messagingSenderId: '36125817771',
    projectId: 'studentsplacementchatbot',
    storageBucket: 'studentsplacementchatbot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqV3K3dSknuswd03zj5bfRdflJRsumo8Y',
    appId: '1:36125817771:ios:4cd554b8a32680153630ee',
    messagingSenderId: '36125817771',
    projectId: 'studentsplacementchatbot',
    storageBucket: 'studentsplacementchatbot.appspot.com',
    iosClientId:
        '36125817771-06101sj331oni6ds7ja52m2m3hpqhq1t.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterchatbotapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqV3K3dSknuswd03zj5bfRdflJRsumo8Y',
    appId: '1:36125817771:ios:4cd554b8a32680153630ee',
    messagingSenderId: '36125817771',
    projectId: 'studentsplacementchatbot',
    storageBucket: 'studentsplacementchatbot.appspot.com',
    iosClientId:
        '36125817771-06101sj331oni6ds7ja52m2m3hpqhq1t.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterchatbotapp',
  );
}
